# Generated by Django 3.2.2 on 2021-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_comentarios_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
